### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM piClim-lu

### ISSUE THREAD

**Issue by Kirkevag** [NorESMhub/noresm2cmor#160]
### Mandatory information:

Hi Yanchun,
this experiment has been CMORized and published already, but there are 
some missing output compared to e.g. piClim-control:

rldscs was requested by RFMIP and is missing, but please do the full
           CFday directory, as for piClim-control. (mo monthly in the model). 
Best,
 - Alf

**Full path to the case(s) of the experiment on NIRD**

/projects/NS9560K/noresm/cases/piClim-lu2deg/

**experiment_id**
RFMIP

**model_id**
e.g.,
NorESM2-LM

**CASENAME(s) and years to be CMORized**

piClim-lu2deg years 1-30

### Optional information
(additional information, if the experiment is branched/hybrid restart from previous parent experiment; you may find more information relevant to the experiment_id here: https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/tables/CMIP6_CV.json)

**parent_experiment_id**
e.g., 
piControl
historical
no parent
etc.,...

**parent_experiment_rip**
e.g., r1i1p1
'no parent'

**parent_time_units**
e.g.,
'days since 0421-01-01'

**branch_method**
e.g.,
'Hybrid-restart from year 1600-01-01 of piControl',

**other information**
(provide other information that might be useful)
e.g., realisation, initialisation, etc...
and the cases name and path to the parent experiment, etc

**Comment by YanchunHe** [comment]
Hi Alf,

This is a task on the queue. There are quite some AerChemMIP and RFMIP experiments in the queue to be processed.

I am redoing the cmorization for all the previously published experiments with additional fields.  I use to NIRD nodes to redo the cmorizations for the existing experiments. 

But since there are newly experiments coming including MM model versions which are slower to process.

So please expect some time before this can be completed.

Best,
Yanchun

**Comment by Kirkevag** [comment]
Thank you, Yanchun,

I wasn't sure if it was akready queued. 

 Best,

 - Alf

**Comment by YanchunHe** [comment]
Yes, I understand. And thanks to open this issue, since otherwise I need to open one in the end :)

You can have a (rough) overview what has been done and what is doing from this script file (but this file is not up-to-date):

https://github.com/NorwegianClimateCentre/noresm2cmor/blob/master/workflow/cmorWrapper.sh

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-lu/r1i1p1f1

**version**
- v20191108

**sha256sum**
- .r1i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@Kirkevag @YanchunHe published

**Comment by Kirkevag** [comment]
Thanks a lot, Alok and Yanchun!

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #271, #272 and #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-lu
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/piClim-lu

**version**
- v20210319

**sha256sum**
- /projects/NS9034K/CMIP6/RFMIP/NCC/NorESM2-LM/piClim-lu
- .r1i1p1f1.sha256sum_v20210319

**Comment by monsieuralok** [comment]
@YanchunHe published
