### ISSUE TITLE
AERday zg500 missing from NorESM2-LM AerChemMIP experiments

### ISSUE THREAD

**Issue by lisesg** [NorESMhub/noresm2cmor#263]
I can't find daily zg500 in the cmorized output from AerChemMIP experiments with NorESM2-LM. I think AERday zg500 is a priority 1 field for AerChemMIP. AerChemMIP does not have daily zg, so I can't just get it from there.

**Comment by oyvindseland** [comment]
I would be surprised if it is missing but have you checked that if it is in the raw output?

**Comment by lisesg** [comment]
I just checked hist-piAer (/projects/NS9560K/noresm/cases/NHISTpiaer_03_f19_tn14_20190909), and it looks like daily Z500 is included in the output, but it does not have Z3.

**Comment by oyvindseland** [comment]
so that specific variable can be cmorized.

**Comment by YanchunHe** [comment]
I will check on this this week.

**Comment by YanchunHe** [comment]
I checked this.

zg500 (Z500) was implemented (#103) after some experiments had been cmorized.

However, a small bug in the namelist file (#238) made the cmorization of zg500 unsuccessful. It was fixed in 09beb6cac27b9ca155e405a8e26472f1c625a50e.

I will redo the cmorization of zg500, together with these iLAMB variables (#262). These AerChemMIP will at least be updated.

I will update under the issues of corresponding experiments.

**Comment by lisesg** [comment]
Thanks Yanchun!

**Comment by YanchunHe** [comment]
These new variables have been cmorized for (most of) the CMIP, AerChemMIP and ScenarioMIP experiments by NorESM2-LM and NorESM2-MM (as refereed by above list). They are in the queue to be published to ESGF.

Close this issue now.
(reopen whenever find needed)
