### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication]  NorESM2-LM historical ensemble member 2  

### ISSUE THREAD

**Issue by oyvindseland** [NorESMhub/noresm2cmor#68]
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/projects/NS9560K/noresm/cases/

**experiment_id**
historical

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
e.g., 
NHIST_02_f19_tn14_20190801   (1850-1949)
NHIST_02_f19_tn14_20190813  (1950-2014)

### Optional information

**parent_experiment_id**
piControl

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
e.g.,
'days since 0421-01-01'

**branch_method**
'Hybrid-restart from year 1631-01-01 of piControl',

**other information**
(provide other information that might be useful)
Ensemble member 2 of historical

**Comment by YanchunHe** [comment]
I found there are some mismatched number of cmorized files between ensemble 1 of historical experiment and other ensemble 2 and 3.

Some fields are in the model output of ensemble 1 but not in 2 and 3, for quite some AERmon fields, e.g., ABS550AL

Some fields between 1850-1949 in ensemble 1 were missing in the cmorized output but available in 1950-2014. (I have not checked this carefully if there were missing in the model output or something wrong with the cmorization.

I think I will publish the ensemble 2 and 3.

Some of these mismatches are also caused by some recent updates of the noresm2cmor tool (although not intended to make the cmorized output of different ensembles different)

There will be a major update of the tool in the near future, and there will be an incremental published of new supported fields including bug-fixes. Hopefully it will alleviates these mismatches between different realisations.

**Comment by YanchunHe** [comment]
(Øyvind)

The problem is that  there are actually a difference in the output between the ensembles.

Ensemble member 1 has a lot more aerosol output (but it make the model markedly slower)

Alle ensemble members have high frequency output after 1950.

Perhaps the information included when asking for cmorization should include the output categories (there are 4 permutations)

**Comment by YanchunHe** [comment]
CMORized and to be published

**data path**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1/

**version**
- v20190920

**other**
- sha256sum updated
- QC passed

**commit**
- 2d52690b8cdb7ad0be84753dd220ab7244ae94ef

**Comment by monsieuralok** [comment]
@YanchunHe @oyvindseland published

**Comment by YanchunHe** [comment]
cmorized with additional fields

**data path**
- /tos-project1/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1/

**version**
- v20191108

**sha256sum**
- .r2i1p1f1.sha256sum_v20191108b

**Comment by monsieuralok** [comment]
@oyvindseland @YanchunHe published

**Comment by YanchunHe** [comment]
Cmorized with additional iLAMB variables (#262), AERday zg500 (#263) and corrected `fNup` (#251).

They are ready to be published to ESGF.

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210203
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

**version**
- v20210203

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
- .r2i1p1f1.sha256sum_v20210203

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
New dataset version to fix issues #270, #273 is ready to be published:

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

**version**
- v20210319

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
- .r1i1p1f1.sha256sum_v20210319

Note, 'dust' variables in AERmon are not available in the model output, so that no updates to #271 #272.

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by YanchunHe** [comment]
cmorized `burtFractionAll` related to issue #286 

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/v20210818
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1

**version**
- v20210818

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical/r2i1p1f1
- .r2i1p1f1.sha256sum_v20210818

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by oyvindseland** [comment]
Asked for additional variables: 6hrPlevPt variables ps and snowmxrat  (1950-2014) and Amon snowmxrat.

**Comment by YanchunHe** [comment]
cmorized `snowmxrat`  for Emon (#82) and 6hrPlevPt (#109).

**data path**
- /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/historical/
- /projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical

**version**
- v20210908

**sha256sum**
/projects/NS9034K/CMIP6/CMIP/NCC/NorESM2-LM/historical
- .r2i1p1f1.sha256sum_v20210908

**Comment by monsieuralok** [comment]
@YanchunHe published

**Comment by monsieuralok** [comment]
@YanchunHe now, ESGF issue is solved; Exactly which data we need to retract and if I am correct then, from all experiments and resolution we need to retract WAP ?

**Comment by YanchunHe** [comment]
> 

All NorESM2-LM, MM, 6hrPlev datasets including `hus` and `wap`. See issue #316

**Comment by monsieuralok** [comment]
@YanchunHe retracted
